### ISSUE TITLE
Module information about threadprivate is not carried across files

### ISSUE THREAD

**Issue by Sezoir** [flang-compiler/f18-llvm-project#1212] opened 2021-11-09 14:47 UTC
## Test case:
Create 2 fortran files, file1.f90 and file2.f90.
In "file1.f90":
```
module private_data
    implicit none

    real, dimension(3) :: thrtest
    !$OMP THREADPRIVATE(thrtest)
end module private_data
```
In "file2.f90":
```
subroutine a()
    use private_data
    thrtest = 1.0

    !$OMP PARALLEL COPYIN(thrtest)
    !$OMP END PARALLEL 
end subroutine a

subroutine b()
    use private_data
    thrtest = 1.0 

    !$OMP PARALLEL 
    !$OMP SINGLE 
    !$OMP END SINGLE COPYPRIVATE(thrtest)
    !$OMP END PARALLEL 
end subroutine b
```
## Expected Result:
Compiles with no complaints.

## Running Result:
```
$ flang-new -fsyntax-only -fopenmp file1.f90 file2.f90
error: Semantic errors in file2.f90
./file2.f90:5:27: error: Non-THREADPRIVATE object 'thrtest' in COPYIN clause
      !$OMP PARALLEL COPYIN(thrtest)
                            ^^^^^^^
./file2.f90:15:34: error: COPYPRIVATE variable 'thrtest' is not PRIVATE or THREADPRIVATE in outer context
      !$OMP END SINGLE COPYPRIVATE(thrtest)
                                   ^^^^^^^
```
## Verification
When compiled with gfortran, e.g `gfortran -fsyntax-only -fopenmp file1.f90 file2.f90`, compiles fine. When compiled without openmp also compiles fine.

**Comment by kiranchandramohan** [comment] 2021-11-09 17:55
Currently, information about OpenMP/OpenACC declarative directives in modules is not carried in the module files. e.g. for the reproducer (file1.f90) given above, we get the module file shown below. 

Information about `threadprivate` (https://www.openmp.org/spec-html/5.0/openmpsu104.html) is usually carried inside flags in Symbols. I think this information is not carried over across compilation units. The question is whether declarative directives should be retained in module files so that it is available in places where the module is used.

```
!mod$ v1 sum:688d4e06cfba0526
module private_data
real(4)::thrtest(1_8:3_8)
end
```

@klausler Could you let us know whether carrying `threadprivate` (and other declarative directive information) is the right way to go? If so, where can this be implemented?

**Comment by klausler** [comment] 2021-11-09 18:03
> Currently, information about OpenMP/OpenACC declarative directives in modules is not carried in the module files. e.g. for the reproducer (file1.f90) given above, we get the module file shown below.
> 
> Information about `threadprivate` (https://www.openmp.org/spec-html/5.0/openmpsu104.html) is usually carried inside flags in Symbols. I think this information is not carried over across compilation units. The question is whether declarative directives should be retained in module files so that it is available in places where the module is used.
> 
> ```
> !mod$ v1 sum:688d4e06cfba0526
> module private_data
> real(4)::thrtest(1_8:3_8)
> end
> ```
> 
> @klausler Could you let us know whether carrying `threadprivate` (and other declarative directive information) is the right way to go? If so, where can this be implemented?

Yes, the extra attributes of OpenMP and OpenACC that apply to module entities need to be present in the module file.  Modules files are emitted by Semantics/mod-file.cpp.

**Comment by PeixinQiao** [comment] 2022-02-09 13:06
@Sezoir @kiranchandramohan Any progress on this? Writing out the declarative attribute in the module file can not only help semantic analysis, it may also help handle the lowering process.

**Comment by kiranchandramohan** [comment] 2022-02-09 13:42
We have not worked on this. Also, we are unlikely to work on this in the next couple of months.

**Comment by PeixinQiao** [comment] 2022-02-09 16:23
@kiranchandramohan Can I take a look at it and try to handle it since it may be prerequisite for lowering threadprivate directive in module when it is declared in module while used in main program?

**Comment by kiranchandramohan** [comment] 2022-02-09 16:29
Sure @PeixinQiao, please go ahead. I will assign this to you.

**Comment by PeixinQiao** [comment] 2022-02-10 12:22
@kiranchandramohan Thanks a lot.

**Comment by PeixinQiao** [comment] 2022-05-12 01:05
This has been supported by https://reviews.llvm.org/rG2cbd4fc4424a88573ee03e2f1dce345f7826e662. The current LLVM (https://github.com/llvm/llvm-project) already supports this. @Sezoir Can you close this?

**Closed** 2022-11-04 14:32 UTC
Labels: Semantics, OpenMP
