### ISSUE TITLE
bbc abort when assigning to a module variable.

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#551] opened 2020-11-10 08:16 UTC
```
cat cm.f90
module cm
  integer :: s
contains
  subroutine c
    s = 5
  end subroutine c
end module cm
```
```
% bbc cm.f90 |& head -11
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bbc cm.f90
 #0 0x000055f40186c0dc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/local/home/sjs/flang/install/bin/bbc+0x2cd50dc)
 #1 0x000055f401869fc4 llvm::sys::RunSignalHandlers() (/local/home/sjs/flang/install/bin/bbc+0x2cd2fc4)
 #2 0x000055f40186a128 SignalHandler(int) (/local/home/sjs/flang/install/bin/bbc+0x2cd3128)
 #3 0x00007f2e6059f8a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #4 0x00007f2e5f265f47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #5 0x00007f2e5f2678b1 abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81:0
 #6 0x000055f3ff07b359 (/local/home/sjs/flang/install/bin/bbc+0x4e4359)
 #7 0x000055f40058b72a (anonymous namespace)::ExprLowering::gen(Fortran::common::Reference<Fortran::semantics::Symbol const>) (.isra.1799) (/local/home/sjs/flang/install/bin/bbc+0x19f472a)
```

**Comment by schweitzpgi** [comment] 2020-11-16 17:48
Should get a "not yet implemented" message now.

**Comment by schweitzpgi** [comment] 2020-11-16 17:51
Duplicate of #317

**Comment by schweitzpgi** [comment] 2020-12-08 17:25
closing dup

**Closed by schweitzpgi** 2020-12-08 17:25 UTC
Labels: Lowering, duplicate
