### ISSUE TITLE
Statement function does not return the correct type

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#247] opened 2020-07-07 08:16 UTC
The type of `I(R)` should be default integer.

```
% cat e351.f
      I(R) = R
      PRINT *, I(2.5)
      END
rome4: flang e351.f
warning: overriding the module target triple with x86_64-unknown-linux-gnu [-Woverride-module]
1 warning generated.
% a.out
 2.5
```

**Comment by tskeith** [comment] 2020-07-07 15:28
I can't reproduce this but that looks like an error from pgfortran, not f18. f18 -fdebug-dump-symbols and -funparse look right to me.

Do you have an f18 command that shows a problem?

**Comment by sscalpone** [comment] 2020-07-07 15:42
Thanks for the pointer.  The symbol tables shows integer.  The first does not have a conversion.

```
    i (Function): Subprogram result:INTEGER(4) i (REAL(4) r)
    Subprogram scope: i size=8 alignment=4
      i (Implicit) size=4 offset=0: ObjectEntity funcResult type: INTEGER(4)
```

```
  %cst = constant 2.500000e+00 : f32
  %2 = call @_FortranAioOutputReal32(%1, %cst) : (!fir.ref<i8>, f32) -> i1
  %3 = call @_FortranAioEndIoStatement(%1) : (!fir.ref<i8>) -> i32
```

**Comment by tskeith** [comment] 2020-07-07 21:48
Suppose `i` were a normal (non-statement) function like this:
```
function i(r)
  i = r
end
```
Then during expression analysis we would generate an analyzed form of the assignment that would look like `i = int(r, kind=4)`.

In the statement function, the analyzed form of the expression should probably also have that conversion in it.

So this probably does need to be fixed in the front end. I think all implicit conversions are supposed to be made explicit so lowering doesn't need to worry about them.

**Comment by jeanPerier** [comment] 2020-07-20 08:09
Thanks Tim, I did not consider that the expression type could be different than the statement function type when implementing statement function lowering. That would be easy to fix in lowering, but I agree with you that it's cleaner to insert the conversion in in the front-end.

**Comment by tskeith** [comment] 2020-07-23 18:20
https://reviews.llvm.org/D84452 should fix this.

**Closed** 2020-07-24 16:07 UTC
Labels: Lowering
