### ISSUE TITLE
VLA capture expression not being used

### ISSUE THREAD

**Issue by mikaoP** [flang-compiler/f18-llvm-project#813] opened 2021-06-02 09:05 UTC
I've noticed when doing an array assign the vla dimensions are recomputed again. Here is an example
```fortran
SUBROUTINE AUX(N)
    IMPLICIT NONE
    INTEGER :: N
    INTEGER :: VLA(N)

    VLA = 1
    PRINT *, VLA
    N = 1
    VLA = 2
    PRINT *, VLA   

END SUBROUTINE AUX

PROGRAM P
    INTEGER :: N

    N = 10

    CALL AUX(N)
END 
```
```
Expected output:
 1 1 1 1 1 1 1 1 1 1
 2 2 2 2 2 2 2 2 2 2
Output:
 1 1 1 1 1 1 1 1 1 1
 2 1 1 1 1 1 1 1 1 1
```

**Comment by jeanPerier** [comment] 2021-06-02 14:13
Thanks for the bug report, I cannot reproduce with the latest HEAD (and a few before this). I get the expected output `2 2 2 2 2 2 2 2 2 2`.

Which version of fir-dev are you using ? How are you compiling end-to-end, are you using opt or directly llc ?

**Comment by mikaoP** [comment] 2021-06-02 14:38
My bad, I've just checked with the current `fir-dev` branch and it works properly

**Comment by jeanPerier** [comment] 2021-06-02 17:15
No problem, VLAs still have some issues due to #796. I am closing this one then.

**Closed by jeanPerier** 2021-06-02 17:15 UTC
